科目ページのURLで発生しているバグの修正&エンター出席バグの関数変更
yudai1204/ScombZ-Utilities pull request #167
Opened 2023-07-31 05:28 UTC by den3asphalt

## 概要

- [x] 主に、科目ページURL指定で使われる?idnumber= を?のみに変更
- [x] Twitterで呟いていたURLの長さで制限をかけていたものの廃止
- [x] エンター出席バグの修正に使っていた関数を新しいものに変更

## 破壊的変更があるか(あれば内容を記載)

- [x] YES
科目ページかどうか判断するのに?idnumberを使わないように、全体を修正

## チェック項目

- [x] ビルドが通る
- [x] 作成した機能が想定通りに動作する
- [x] スマートフォンサイズで表示確認を行った
- [x] warning が増えていない
- [x] 複雑なコードにはコメントを記載してある

## リリースノートへの記述
### 種別
- [x] optimisation - 既存機能修正・最適化
- [x] bugfix - バグ修正
- [ ] newfunc - 新機能追加
- [ ] style - スタイル変更
- [ ] else - その他

### タイトル
一部機能の修正

### 詳細
特定の状況において科目ページ内の機能が上手く働かない問題を修正しました。
また、一部関数の最適化を行いました。

## 関連Issue
#161 Fixed.

## コメント
ワーニングが増えていたので出席バグ周りの方の問題も修正しました。
正しく動作するはずですが、実際に出席が使える状況になってみないと微妙です。

2023-07-31 09:40 UTC, yudai1204 commented
「リリースノートへの記述」項目は1つのみ選択してください。複数の機能をアップデートした場合は、それぞれに対してタイトルと詳細を記述してください。

2023-07-31 11:54 UTC, den3asphalt commented
> 「リリースノートへの記述」項目は1つのみ選択してください。複数の機能をアップデートした場合は、それぞれに対してタイトルと詳細を記述してください。

使い方がわかってなくて申し訳ありません、只今修正します。

2023-08-31 10:16 UTC, saka-naname commented on ScombZ Utilities/js/layoutSubject.js
> +        if (target){
この条件式だと`#attendances_send_set`が見つかった場合に625行目の`observer.observe()`に到達できず、エンターバグを修正するコードが実行できなくなってしまうと思います。

```suggestion
        if (!target){
```

2023-08-31 10:34 UTC, saka-naname requested changes
URL判定に関する部分に関しては問題ないと思います。エンター出席バグを修正するコードの変更に関して、誤りと思われるコードを発見したので確認をお願いします。

2023-08-31 14:37 UTC, den3asphalt commented on ScombZ Utilities/js/layoutSubject.js
> +        if (target){
その通りです、稚拙なミスで大変申し訳ございません……

2023-08-31 14:42 UTC, den3asphalt commented
> URL判定に関する部分に関しては問題ないと思います。エンター出席バグを修正するコードの変更に関して、誤りと思われるコードを発見したので確認をお願いします。

こちら、頂いた修正を反映しcommitしました。レビューしていただきありがとうございます。

2023-09-01 09:13 UTC, saka-naname approved these changes

2023-09-01 09:13 UTC, saka-naname commented
確認しました、ありがとうございます！大丈夫そうなのでApproveしました

2023-09-02 14:36 UTC, merged

2023-09-02 14:37 UTC, saka-naname commented
Mergeしました 🚀