通知を消すボタンの実装、またボタン周りの大きさ調整
yudai1204/ScombZ-Utilities pull request #71
Opened 2022-06-01 06:22 UTC by den3asphalt

最新のものを持ってきて調整しました。
commitも最小限にしました。

内容としては通知を消すボタンの追加、並びにボタン周りのcss調整です。layout.jsに手を加えることも考えたのですが、衝突のことを考えてclearButton.jsに記述しています。
通知削除ボタンなどを使い積極的に通知を消す人でないと気付かないレベルの崩れなので、これでもあまり問題はないと思われます。

また何かございましたらレビューにて教えていただけると幸いです。

2022-06-01 12:34 UTC, yudai1204 requested changes
バグを除いて全体的に問題はないです。
要望が一店あるとすれば、誤クリックで消えてしまったり、テスト中に押してしまうことを防止するために、本当に消すかの確認ダイアログを出してほしいです。

2022-06-01 12:34 UTC, yudai1204 commented on ScombZ Utilities/js/clearButton.js
> +            location.reload(true);
**バグ**
正常に動かない問題があります。
バグの内容: 削除ボタンを押しても通知が削除されない
原因: ajaxは非同期関数です。処理が完了するより前にreloadされているため削除されません。処理が完了したのを確認してからリロードするか、ページ全体をリロードせずにヘッダだけリロードしてください

2022-06-01 12:46 UTC, den3asphalt commented on ScombZ Utilities/js/clearButton.js
> +            location.reload(true);
承知しました。直させていただきます。

2022-06-01 12:54 UTC, yudai1204 commented on ScombZ Utilities/js/clearButton.js
> +            location.reload(true);
表示上消えればいいので、リロードせずにliの中身をremoveして、赤い通知マークを非表示にするだけでいいと思います

2022-06-01 13:03 UTC, den3asphalt commented on ScombZ Utilities/js/clearButton.js
> +            location.reload(true);
変にリロード挟むよりよっぽどスマートですね……そのようにさせて頂きます。アドバイス感謝です。

2022-06-01 13:24 UTC, yudai1204 commented on ScombZ Utilities/js/clearButton.js
> +            location.reload(true);
確認ダイアログも誤クリック防止のためつけてほしいです

2022-06-01 21:32 UTC, yudai1204 approved these changes

2022-06-01 21:32 UTC, merged

2022-06-01 21:45 UTC, yudai1204 commented
自分で直すのでいいですが、ユーザビリティに配慮して日本語を書いてください

タイトル:更新通知ボタンの右側に全ての更新通知を削除するボタンを追加
本文: 更新通知ボタンの右側に全ての更新通知を削除するボタンを追加

とか書かれても、タイトルは長過ぎてわかりづらいし、本文はタイトルそのまま写しただけだし修飾語が足りなくて分かりにくいです。前にも言ったと思いますが、ユーザーは基本的にコードを読まずこの文だけを読みます。設定画面だけで詳細に分かるようにしてください。タイトルを長くし過ぎないでください。分かりにくいものは画像を挿入してどうなるのか視覚的に明示してください。コード本体と同じくらい設定画面は大切なので、ここをサボられると困ります。

2022-06-02 12:12 UTC, den3asphalt commented
申し訳ございませんでした。ユーザビリティに対しての理解が足りませんでした。